### ISSUE TITLE
Setup GitHub Pages for Truffle 🚀

### ISSUE THREAD

**Issue by abxhr** [aibits-dxb/Truffle#2]
As folks prefer to use a website rather than view content in GitHub, I believe it will be best if we work on creating a webpage for Truffle (*just like how we have done for [Openlib.cs](https://openlib-cs.acmbpdc.org/)*). We could use `mkdocs` itself (for now) to create the webpage. 

- [x] Configure `mkdocs` for this repository
- [x] Use custom domain
- [x] Setup GitHub Actions to deploy the website every time a commit is done to the repository

**Comment by abxhr** [comment]
@datdhruv Firas has setup `mkdocs` for the repository along with the required `ci`. Could you work on setting up the custom domain?

**Comment by datdhruv** [comment]
Done
